name: Deploy to Musicdex (Staging)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd /opt/alpha_musicdex_web || { echo "No directory found"; exit 1; } 
            git pull origin dev
            yarn
            yarn run build
            rm -r /var/www/html/musicdex-alpha.holodex.net/*
            cp -r build/* /var/www/html/musicdex-alpha.holodex.net/
