name: Deploy to Musicdex (Production)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script_stop: true
          script: |
            cd /opt/prod_musicdex || { echo "No directory found"; exit 1; } 
            git pull origin master
            yarn
            yarn run build
            rm -r /var/www/html/music.holodex.net/*
            cp -r build/* /var/www/html/music.holodex.net/
      - name: Purge Cloudflare Cache
        uses: indiesdev/curl@v1
        with:
          url: "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache"
          method: "POST"
          headers: '{ "X-Auth-Key": "${{ secrets.CF_CACHE_PURGE }}", "X-Auth-Email": "${{ secrets.CLOUDFLARE_AUTH_EMAIL }}", "Content-Type": "application/json" }'
          body: '{"files":["https://holodex.net/index.html", "https://holodex.net/sw.js"]}'
          timeout: 10000
