name: mate

on: [push, pull_request]

jobs:
  test:
    name: mate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Deploy React app to GitHub Pages
        uses: omkartapale/react-deployment-gh-pages@v1.0.0
