name: mate

on: [push, pull_request]

jobs:
  test:
    name: mate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - run: yarn
      - run: yarn build

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          push_options: "--force"
          repository: "./build/"

      # - run: git config user.name github-actions
      # - run: git config user.email github-actions@github.com
      # - run: git --work-tree build add --all
      # - run: git commit -m "Automatic Build and Deploy run by GitHub Actions"
      # - run: git push origin HEAD:gh-pages --force
